config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get    '/help',      to: 'static_pages#help'
get    '/faq',       to: 'static_pages#faq'
get    '/parentfaq', to: 'static_pages#parentfaq'
get    '/about',     to: 'static_pages#about'
get    '/contact',   to: 'static_pages#contact'
get    '/privacy',   to: 'static_pages#privacy'

devise_for :users, :controllers => { registrations: 'registrations' }

resources :profiles, only: [:create]
resources :profiles_sessions, only: [:create]
resources :parentmode_sessions, only: [:new, :create, :destroy, :update]
resources :videos, only: [:show, :index, :create, :update, :destroy]
post     '/preload_video', to: 'videos#preload'
resources :tags, only: [:index]
resources :settings, only: [:index, :update]
end

app/models/profile.rb
class Profile < ApplicationRecord
  include SettingsHelper

  belongs_to :user
  has_many :profile_settings, dependent: :destroy
  has_many :settings, through: :profile_settings
  has_many :videos, dependent: :destroy
  validates :user_id, presence: true
  validates :name, presence: true, allow_blank: false,
            uniqueness: { scope: :user_id, message: "Profile name already taken" }
  after_save :set_profile_settings

  def self.user_id(profile_id)
    Profile.where(id: profile_id).pluck(:user_id).first
  end

  private
    def set_profile_settings
      set_profile_missing_defaults(id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    include ApplicationHelper

    before_action :logged_in_user, only: [:create]
    before_action :parent_user, only: [:create]
    
    def create
        @profile = current_user.profiles.build(profiles_params)
        if @profile.save
            flash[:notice] = "Profile saved!"
        else
            flash[:alert] = "Profile not saved!"
        end
        
        load_profiles
        
        respond_to do |format|
            format.html { redirect_back fallback_location: root_url }
            format.js
        end
    end
    
    private
    
        def profiles_params
            params.require(:profiles).permit(:name)
        end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile_form.html.erb
<div id="profile-form">
  <p><strong>Add a Profile:</strong></p>
  <%= form_for(:profiles, url: profiles_path, remote: true) do |f| %>
    <%= f.label :name, class: 'col-form-label col-form-label-lg' %>
    <%= f.text_field :name, value: "", class: 'form-control input-lg' %>
    <%= f.submit "Submit", class: 'btn-lg btn-primary' %>
  <% end %>
</div>

app/views/profiles/_profile_list.html.erb
<div id='curr-profile-wrapper'><p><strong>Current profile:</strong></p><p id='curr-profile'><%= current_profile_name %></p></div>
<% if !parent_mode? %>
  <%= link_to 'Parent Mode', new_parentmode_session_path, id: 'btn-prnt-mode', class: 'btn-lg btn-primary' %>
<% else %>
  <%= form_for(:parentmode, url: parentmode_session_path(current_user.id), method: :put) do |f| %>
    <% if review_mode? %>
      <%= f.hidden_field :mode, value: 'manage' %>
      <%= f.submit "Manage Videos", class: 'btn-lg btn-primary' %>
    <% else %>
      <%= f.hidden_field :mode, value: 'review' %>
      <%= f.submit "Review Videos", class: 'btn-lg btn-primary' %>
    <% end %>
  <% end %>
<% end %>
<div id='profiles-list-wrapper'>
  <p><strong>Profiles:</strong></p>
  <div id="profile-list" class="btn-group-vertical">
     <% if @profiles.count == 0 %>
       <p>No Profiles</p>
     <% else %>
       <% @profiles.each do |p| %>
         <%= button_to "#{p.name}", profiles_sessions_path(name: p.name), method: :post, id: 'profile-btn', class: 'btn btn-lg', remote: true %>
       <% end %>
     <% end %>
  </div>
</div>

app/views/profiles/_profile_page.html.erb
<div class="row">
<%= render 'profiles/profile_section' %>
<%= render 'profiles/video_list', :div_class => "col-md-10" unless @videos.nil? %>
</div>

app/views/profiles/_profile_section.html.erb
<div id="profiles_wrapper" class="col-md-2">
    <div id='profiles'>
    <%= render 'profiles/profile_list' %>
    </div>
    <%= render 'profiles/profile_form' if parent_mode?  %>
    <% if parent_mode? %>
        <%= button_to("Exit Parent Mode", parentmode_session_path(current_user.id), method: :delete, class: 'btn-lg btn-primary')  %>
    <% end %>
</div>

app/views/profiles/_video_list.html.erb
<p>Click on a thumbnail to load it into the the player</p>
<% @videos.each do |v| %>
  <div id="mng-wrapper">
    <div id="vidframe">
	<% if manage_mode? %>
          <%= image_tag v.thumbnail.url, alt: 'thumbnail:' + v.title,  title: v.title, class: 'vid-thumbnail'%>
	<% else %>
          <a href="<%= video_path(v) %>" data-remote="true"><%= image_tag v.thumbnail.url, alt: 'thumbnail:' + v.title,  title: v.title, class: 'vid-thumbnail'%></a>
    <% end %>
    </div>
    <% if parent_mode? %>
        <div id="mngbuttons">
            <%= form_for(:video, url: video_path(v), method: :patch, remote: true) do |f| %>
		<% if review_mode? %>
                  <%= f.hidden_field :approved, value: 'true' %>
		  <%= f.submit "Approve", id: 'mng-aprve-del-btn', class: 'btn-lg btn-primary' %>
		 <% else %>
                  <%= f.hidden_field :approved, value: 'false' %>
		  <%= f.submit "Review", id: 'mng-aprve-del-btn', class: 'btn-lg btn-primary' %>
	         <% end %>
            <% end %>
	    <%= link_to "Delete", video_path(v), method: :delete, remote: true, data: { confirm: 'Delete: Are you sure?' }, id: "mng-del-btn", class: 'btn-lg btn-primary' %>
        </div>
    <% end %>
  </div>
<% end %>
<div id="video-paginate">
    <% if parent_mode? %>
	    <%= will_paginate @videos, params: { controller: 'videos', action: 'index', tags: { name: get_search_key } } %>
    <% else %>
	    <%= will_paginate @videos, params: { controller: 'videos', action: 'index', tags: { name: get_search_key }} %>
    <% end %>

</div>

app/views/profiles/create.js.erb
$('#notice').html('<%= flash[:notice] %>');
$('#alert').html('<%= flash[:alert] %>');
$('#profiles_name').val('');
$('#profiles').html('<%= escape_javascript(render('profiles/profile_list')) %>');