config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get    '/help',      to: 'static_pages#help'
get    '/faq',       to: 'static_pages#faq'
get    '/parentfaq', to: 'static_pages#parentfaq'
get    '/about',     to: 'static_pages#about'
get    '/contact',   to: 'static_pages#contact'
get    '/privacy',   to: 'static_pages#privacy'

devise_for :users, :controllers => { registrations: 'registrations' }

resources :profiles, only: [:create]
resources :profiles_sessions, only: [:create]
resources :parentmode_sessions, only: [:new, :create, :destroy, :update]
resources :videos, only: [:show, :index, :create, :update, :destroy]
post     '/preload_video', to: 'videos#preload'
resources :tags, only: [:index]
resources :settings, only: [:index, :update]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "error") %> occcured.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_parent_page_btn.html.erb
<%= form_for(:tags, url: videos_path, method: :get) do |f| %>
  <%= f.hidden_field :name, value: get_search_key %>
  <%= f.submit "Parent Page", class: 'btn-lg btn-primary' %>
<% end %>

app/views/shared/_profile_form.html.erb
<div class="col-md-3">
  <p>Add a Profile</p>
  <%= form_for(:profiles, url: profiles_path) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, value: "", autofocus: true, class: 'form-control' %>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shared/_tag_search.html.erb
<div id='search-form-wrapper'>
<%= render 'tags/search', locals: { clear_tag: false } %>
</div>

app/views/shared/_video_frame.html.erb
<div><p><strong>Title: </strong><%= curr_vid_title %></p></div>
<% # sandbox is not there for security, but to prevent clicking out of the iframe as its attribute negate any security %>
<%= content_tag(:iframe, '', width: 560, height: 315, src: curr_vid_url.html_safe, sandbox: "allow-scripts allow-same-origin") %>

app/views/shared/_video_select.html.erb
<% if parent_mode? %>
  <div id="video_list_wrapper" class="<%= review_mode? ? 'col-md-5' : 'col-md-9' %>">
<% else %>
  <div id="video_list_wrapper" class="col-md-5">
<% end %>
  <%= render 'shared/tag_search' %>
  <div id="video_list">
    <%= render 'profiles/video_list' unless @videos.nil? %>
  </div>
</div>