config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get    '/help',      to: 'static_pages#help'
get    '/faq',       to: 'static_pages#faq'
get    '/parentfaq', to: 'static_pages#parentfaq'
get    '/about',     to: 'static_pages#about'
get    '/contact',   to: 'static_pages#contact'
get    '/privacy',   to: 'static_pages#privacy'

devise_for :users, :controllers => { registrations: 'registrations' }

resources :profiles, only: [:create]
resources :profiles_sessions, only: [:create]
resources :parentmode_sessions, only: [:new, :create, :destroy, :update]
resources :videos, only: [:show, :index, :create, :update, :destroy]
post     '/preload_video', to: 'videos#preload'
resources :tags, only: [:index]
resources :settings, only: [:index, :update]
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_many :profile_settings, dependent: :destroy
  has_many :general_settings, dependent: :destroy
  validates :name, :setting_type, presence: true
  validates_inclusion_of :setting_type, :in => ['general','profile']
  validates_inclusion_of :default_value, :in => :allowed_values, if: :strict_values

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  include ApplicationHelper, SettingsHelper

  before_action :logged_in_user, only: [:index, :update]
  before_action :parent_user, only: [:index, :update]

  def index
    @profile_settings = User.find(current_user.id).profile_settings
  end

  def update
    # Since can't serialize data on a HTML doc yet, javascript intercepts
    # the submit, serializes the form data, and makes an ajax call to this
    # named route.
    #
    settings = settings_params

    any_changed = false

    all_succeeded = true

    settings['profiles'].each do |s|
      setting = ProfileSetting.find_by(profile_id: s['profile_id'].to_i, \
                                       setting_id: s['setting_id'].to_i)
      
      if setting.value != s['value']
        setting.update_attribute(:value, s['value'])

        all_succeeded &= setting.save

        any_changed = true
      end

      if all_succeeded
        flash[:notice] = 'All updated suceeded'
      else
        flash[:alert] = 'Some or all updates failed.' if any_changed
      end

      flash[:notice] = 'Nothing to save' if !any_changed && all_succeeded
    end

    redirect_to settings_path
  end

  private
    def settings_params
      params.require(:settings).permit(:profiles => [ :profile_id, :setting_id, :value ])
    end
end

app/helpers/settings_helper.rb
module SettingsHelper

  def strict_values(setting_id)
    Setting.find(setting_id).strict_values
  end

  def setting_options(setting_id)
    Setting.find(setting_id).allowed_values.gsub(' ','').split(',')
  end

  def get_profile_settings(profile_id)
    Profile.find(profile_id).profile_settings
  end

  def set_profile_missing_defaults(profile_id)
    settings = get_profile_settings(profile_id)

    # Get missing settings
    missing = Setting.select(:id, :default_value).where(setting_type: 'profile').where.not(id: settings.map(&:setting_id))

    missing.each do |m|
      ProfileSetting.create(profile_id: profile_id, setting_id: m.id, value: m.default_value)
    end
  end

  def set_all_profile_missing_defaults
    profiles = User.find(current_user.id).profiles

    profiles.each do |p|
      set_profile_missing_defaults(p.id)
    end
  end
end

app/views/settings/index.html.erb
<% provide(:title, "Application Settings") %>
<div class='col-md-4'>
<%= render 'shared/parent_page_btn' %>
<h3>Profile Settings:</h3>
<% c_profile_id = 0 %>
<%= form_tag(setting_path(current_user.id), id: 'profile-settings', method: :put) do %>
<%= hidden_field_tag 'user_id', current_user.id %>
<%  for setting in @profile_settings %>
  <% if setting.profile_id != c_profile_id %>
    <h4><%= Profile.find(setting.profile_id).name %></h4> 
    <% c_profile_id = setting.profile_id %>
  <% end %>
  <%= hidden_field_tag 'settings[profiles][][profile_id]', c_profile_id %>
  <% setting_name = Setting.find(setting.setting_id).name %>
  <%= label_tag setting_name, nil, class: 'col-form-label col-form-label-lg' %>
  <%= hidden_field_tag 'settings[profiles][][setting_id]', setting.setting_id %>
  <% if strict_values(setting.setting_id) %>
    <%= select_tag 'settings[profiles][][value]', options_for_select(setting_options(setting.setting_id), setting.value), class: 'form-control input-lg' %>
  <% else %>
    <%= text_field_tag 'settings[profiles][][value]', html_escape(setting.value), class: 'form-control input-lg' %>
  <% end %>
  </br>
<% end %>
<%= submit_tag 'Submit', class: 'btn-lg btn-primary' %>
<% end %>