config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get    '/help',      to: 'static_pages#help'
get    '/faq',       to: 'static_pages#faq'
get    '/parentfaq', to: 'static_pages#parentfaq'
get    '/about',     to: 'static_pages#about'
get    '/contact',   to: 'static_pages#contact'
get    '/privacy',   to: 'static_pages#privacy'

devise_for :users, :controllers => { registrations: 'registrations' }

resources :profiles, only: [:create]
resources :profiles_sessions, only: [:create]
resources :parentmode_sessions, only: [:new, :create, :destroy, :update]
resources :videos, only: [:show, :index, :create, :update, :destroy]
post     '/preload_video', to: 'videos#preload'
resources :tags, only: [:index]
resources :settings, only: [:index, :update]
end

app/views/layouts/_header.html.erb
<header>
<div class="container">
  <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
	  <li class="navbar-left navbar-text">Account Type: <%= AccountType.type_name(current_user.account_type_id).capitalize %></li>
          <li class="navbar-left navbar-text" id="video-count">Videos: <%= video_count_display %> </li>
       <% end %>
       <li class="active"><%= link_to app_name, root_path %></li>
       <li class="navbar-right"><%= link_to "Privacy", privacy_path, target: :_blank %></li>
       <li class="navbar-right"><%= link_to "About",  about_path, target: :_blank  %></li>
       <li class="navbar-right"><%= link_to "FAQ",    faq_path, target: :_blank  %></li>
       <li class="navbar-right"><%= link_to "Help",   help_path, target: :_blank %></li>
       <% if user_signed_in? %>
         <li class="navbar-right dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
         <ul class="navbar-right dropdown-menu">
           <% if parent_mode? %>
             <li class="navbar-right"><%= link_to "Account Details", edit_user_registration_path %></li>
             <li class="navbar-right"><%= link_to "Cancel Account", user_registration_path, data: { confirm: "Cancel account: Are you sure?" }, method: :delete %></li>
              <li class="navbar-right divider"></li>
              <li class="navbar-right"><%= link_to "Application Settings", settings_path %></li>
              <li class="navbar-right"><%= link_to "Parent FAQ", parentfaq_path %></li>
           <% end %>
           <li class="navbar-right divider"></li>
           <li class="navbar-right"> <%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
         </ul>
        </li>
        <li class="navbar-right"><%= link_to "Home",   root_path %></li>
        <% else %>
          <li class="navbar-right"><%= link_to "Log in", user_session_path %></li>
        <% end %>
      </ul>
    </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Kid friendly YouTube viewer. Kids view videos that their parents review and approve first."
  <meta name="google-site-verification" content="95LJbxl1jFiTte--z-oN6aw7BBOmCAqq_972VRIUBrM" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<% if !user_signed_in? %>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "VideoObject",
  "name": "Your Family UTube Demo",
  "description": "Watch a brief demonstration of the basic funtions of the Your Family UTube application",
  "thumbnailUrl": "http://i3.ytimg.com/vi/4jsnQgwb0Lo/maxresdefault.jpg",
  "uploadDate": "2017-10-30T04:33:00-04:00",
  "duration": "PT3M02S",
  "publisher": {
    "@type": "Organization",
    "name": "Vast Dawn Software",
    "logo": "https://familyutube.herokuapp.com/favicon.ico"
  },
  "contentUrl": "https://youtu.be/4jsnQgwb0Lo",
  "embedUrl": "<iframe width='560' height='315' src=;https://www.youtube.com/embed/4jsnQgwb0Lo' frameborder='0' allowfullscreen></iframe>"
}
</script>
<% end %>
</head>
<body>
<%= render 'layouts/header' %>
<div id="app_notices">
  <p id="notice" class="notice"><%= notice %></p>
  <p id="alert" class="alert"><%= alert %></p>
</div>
<%= yield %>
</body>
</html>